name 'chef-server'
run_list 'role[habitat]'
default_source :supermarket
cookbook 'chef-client', '~> 12.3.3'
cookbook 'elasticsearch', '~> 4.3.0'
cookbook 'grafana', '~> 9.6.0'
cookbook 'habitat', '~> 2.2.4'
cookbook 'influxdb', git: 'https://github.com/kuritsu/chef-influxdb.git', branch: 'master'
cookbook 'java', '~> 8.6.0'
cookbook 'jenkins', '~> 8.2.1'
cookbook 'nginx', '~> 11.5.0'
cookbook 'telegraf', '~> 0.12.0'
