name 'chef-server'
run_list 'role[habitat]'
default_source :supermarket
cookbook 'habitat', '~> 2.2.4'
cookbook 'java', '~> 8.6.0'
cookbook 'jenkins', '~> 8.2.1'
cookbook 'chef-client', '~> 12.3.3'
cookbook 'elasticsearch', '~> 4.3.0'
cookbook 'grafana', '~> 9.6.0'
cookbook 'kibana', '~> 0.2.3'
cookbook 'logstash_lwrp', '~> 2.1.0'
cookbook 'nginx', '~> 11.5.0'
