{
 "title": "statsd-k8s",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": true,
 "panels": [
  {
   "title": "CPU usage by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "io.kubernetes.pod.namespace" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory usage by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "io.kubernetes.pod.namespace" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "max_usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage and capacity per ns",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "namespace" ], "type": "tag" }
     ],
     "measurement": "kubernetes_pod_volume",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "namespace" ], "type": "tag" }
     ],
     "measurement": "kubernetes_pod_volume",
     "select": [
      [
       { "params": [ "capacity_bytes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "App Exit Codes per pod names",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "io.kubernetes.pod.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "exitcode" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}