#!/bin/bash
#
# Install Chef Infra Client and assign a role to the current node, installing
# all extra software required for the role.
# Vars:
#   NODE_NAME:  Node name.
#   NODE_ENV:   Node environment. Ex: stg, prd
#   NODE_ROLE:  Node role. Check the list of possible roles/policies in the
#               policyfiles dir of this repo.
#   NODE_ORG:   Organization ID. Alphanumeric & all lowercase.
#   CHEF_SERVER_HOSTNAME: Chef Server public/private URL, including the
#               /organizations/org path and port.
#               Ex. https://chef.internal:5443/organizations/mycompany
#   VALIDATE_PEM_FILE: Organization pem file path (generated by the
#                      install-chef-server.sh script).
#

rpm -Uvh https://packages.chef.io/files/stable/chef/16.10.17/el/8/chef-16.10.17-1.el7.x86_64.rpm

cp $VALIDATE_PEM_FILE /etc/chef/validation.pem

cat >/etc/chef/client.rb <<EOF
log_location     STDOUT
ssl_verify_mode  :verify_none
chef_server_url  '$SERVER_URL'
node_name        '$NODE_NAME'
validation_key   '/etc/chef/validation.pem'
policy_group     '$NODE_ENV'
policy_name      '$NODE_ROLE'
use_policyfile   true
json_attribs     '/etc/chef/attr.json'
EOF

test ! -f "/etc/chef/attr.json" && echo "{}" >/etc/chef/attr.json

chef-client --chef-license=accept

echo "===> Chef Infra client and node role installed."
echo "===> IMPORTANT:Remove the validation keys manually."
