#!/bin/bash
#
# Install Chef Infra Client and assign a role to the current node, installing
# all extra software required for the role.
# Vars:
#   NODE_NAME:  Node name.
#   NODE_ENV:   Node environment. Ex: stg, prd
#   NODE_ROLE:  Node role. Check the list of possible roles/policies in the
#               policyfiles dir of this repo.
#   NODE_ORG:   Organization ID. Alphanumeric & all lowercase.
#   CHEF_SERVER_HOSTNAME: Chef internal/external hostname.
#   VALIDATE_PEM_FILE: Organization pem file path (generated by the
#                      install-chef-server.sh script).
#   CHEF_SERVER_CERT: SSL Certificate file path from Chef Server load balancer (to be trusted).
#

rpm -Uvh https://packages.chef.io/files/stable/chef/16.10.17/el/8/chef-16.10.17-1.el7.x86_64.rpm

cp $VALIDATE_PEM_FILE /etc/chef/validation.pem

cat >/etc/chef/client.rb <<EOF
log_location     STDOUT
ssl_verify_mode  :verify_none
chef_server_url  'https://$CHEF_SERVER_HOSTNAME/organizations/$NODE_ORG'
node_name        '$NODE_NAME'
validation_key   '/etc/chef/validation.pem'
environment      '$NODE_ENV'
EOF

mkdir -p ~/.chef

cat >~/.chef/config.rb <<EOF
ssl_verify_mode  :verify_none
chef_server_url  'https://$CHEF_SERVER_HOSTNAME/organizations/$NODE_ORG'
EOF

knife ssl fetch

chef-client -r role[${NODE_ROLE}] --chef-license=accept

echo "===> Chef Infra client and node role installed."
echo "===> IMPORTANT:Remove the validation keys manually."
